name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools-preview
          targets: thumbv8m.main-none-eabihf

      - run: cargo install cargo-binutils
      - run: cargo fmt -- --check
      - run: cargo clippy --target thumbv8m.main-none-eabihf
